import os
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from tqdm import tqdm
from ...immutables import ProjectPaths

# Configuration
NUM_FOLDS = 5
SEED = 42
AUGMENTATION_SUFFIXES = [
    '_resized',
    "_hflip_noise",
    "_hvflip_brightcont",
    "_symm_shit_blur",
    '_rotate20_elastic',
    "_gridshuffle",
    "_cutout",
]

def parse_image_name(image_name_from_file):
    """Parses filename to extract base name (Patient_Side_View) and suffix."""
    name_no_ext = image_name_from_file.split('.')[0]
    for suffix in AUGMENTATION_SUFFIXES:
        if name_no_ext.endswith(suffix):
            base_name = name_no_ext[:-len(suffix)]
            return base_name, suffix
    return name_no_ext, ""

def get_patient_id(image_name):
    """Extracts Patient ID (e.g., 'P1') from 'P1_L_CM_MLO...'."""
    return image_name.split('_')[0]

def main():
    print(f"--- Generating {NUM_FOLDS}-Fold Splits ---")
    
    # 1. Load Consistent Annotations (Ground Truth)
    df = pd.read_csv(ProjectPaths.annotations_consistent_harmonized)
    
    # Group by Patient to ensure no leakage
    # We take the 'max' label for stratification (if patient has 1 Malignant view, they count as Malignant)
    label_map = {"Benign": 0, "Malignant": 1, "Normal": 2}
    df['label_idx'] = df['Pathology Classification/ Follow up'].map(label_map)
    
    patient_groups = df.groupby('Patient_ID')['label_idx'].max().reset_index()
    X = patient_groups['Patient_ID'].values
    y = patient_groups['label_idx'].values

    # 2. Generate Folds
    skf = StratifiedKFold(n_splits=NUM_FOLDS, shuffle=True, random_state=SEED)
    
    fold_patient_map = {} # {fold_idx: {'train': {p1, p2...}, 'val': {p3, p4...}}}

    print("Stratifying patients...")
    for fold_idx, (train_idx, val_idx) in enumerate(skf.split(X, y)):
        fold_patient_map[fold_idx] = {
            'train': set(X[train_idx]),
            'val': set(X[val_idx])
        }
        
        # Print distribution stats
        train_labels = y[train_idx]
        val_labels = y[val_idx]
        print(f"Fold {fold_idx}: Train Patients: {len(train_idx)}, Val Patients: {len(val_idx)}")
        print(f"  - Train Dist: {np.bincount(train_labels)}")
        print(f"  - Val Dist:   {np.bincount(val_labels)}")

    # 3. Read All Augmented Annotations
    # We load all available augmented files from the text file generated by augmentation script
    try:
        with open(ProjectPaths.cls_annotations, 'r') as f:
            all_annotation_lines = f.readlines()
    except FileNotFoundError:
        print(f"Error: {ProjectPaths.cls_annotations} not found. Run augmentation script first.")
        return

    # 4. Assign Lines to Folds based on Rules
    # Rule 1: Only keep CM images (or DM) as anchor, consistent with split_train_valid.py logic
    # Rule 2: Train gets all augmentations. Val gets ONLY '_resized'.
    
    # Initialize file handlers dictionary
    fold_files = {}
    for i in range(NUM_FOLDS):
        t_path = os.path.join(ProjectPaths.cls_dataset, f"train_annotations_fold_{i}.txt")
        v_path = os.path.join(ProjectPaths.cls_dataset, f"val_annotations_fold_{i}.txt")
        fold_files[i] = {
            'train_path': t_path, 'val_path': v_path,
            'train_lines': [], 'val_lines': []
        }

    print("Distributing image lines into folds...")
    for line in tqdm(all_annotation_lines):
        line = line.strip()
        if not line: continue
        
        image_name = line.split()[0]
        
        # Rule: Only include CM lines (Dataset loader infers DM pair)
        if '_DM_' in image_name:
            continue
            
        base_name, suffix = parse_image_name(image_name)
        pid = get_patient_id(image_name)
        
        for fold_idx in range(NUM_FOLDS):
            patients = fold_patient_map[fold_idx]
            
            # If patient is in Train group for this fold
            if pid in patients['train']:
                # Train gets everything (Resized + Augments)
                fold_files[fold_idx]['train_lines'].append(line + "\n")
                
            # If patient is in Val group for this fold
            elif pid in patients['val']:
                # Val gets ONLY resized images (No geometric/pixel augments)
                if suffix == '_resized':
                    fold_files[fold_idx]['val_lines'].append(line + "\n")

    # 5. Save Files
    for i in range(NUM_FOLDS):
        t_path = fold_files[i]['train_path']
        v_path = fold_files[i]['val_path']
        
        with open(t_path, 'w') as f:
            f.writelines(fold_files[i]['train_lines'])
            
        with open(v_path, 'w') as f:
            f.writelines(fold_files[i]['val_lines'])
            
        print(f"Saved Fold {i}:")
        print(f"  - Train: {len(fold_files[i]['train_lines'])} images -> {t_path}")
        print(f"  - Val:   {len(fold_files[i]['val_lines'])} images -> {v_path}")

if __name__ == "__main__":
    main()